name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Test
      run: dotnet test --no-build -- --coverage --coverage-output-format xml --coverage-output coverage.xml  --configuration Release --verbosity normal
    
    - name: Generate Report
      run: ReportGenerator -reports:Xeyth.Result.Tests\bin\Release\net9.0\TestResults\coverage.xml -targetdir:CoverageReport

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: CoverageReport/