name: Publish Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Set Version from Git Tag
      id: version
      run: |
        VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')  # Extract version from tag
        echo "Version=${VERSION}" >> $GITHUB_ENV

    - name: Update .csproj with Version
      run: sed -i "s/<Version>.*<\/Version>/<Version>${{ env.VERSION }}<\/Version>/" Xeyth.Result/Xeyth.Result.csproj

    - name: Pack
      run: |
        dotnet nuget verify
        dotnet pack ./Xeyth.Result/Xeyth.Result.csproj --no-build --configuration Release -o ./artifacts

    - name: Publish Packages
      if: success()  # Only run if previous steps succeed
      run: | 
        dotnet nuget add source --username Xeythhhh --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Xeythhhh/index.json"
        dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
        dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"
