name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Set Version from Git Tag
      id: version
      run: |
        VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')  # Extract version from tag
        echo "Version=${VERSION}" >> $GITHUB_ENV

    - name: Update .csproj with Version
      run: |
        sed -i "s/<Version>.*<\/Version>/<Version>${{ env.VERSION }}<\/Version>/" Xeyth.Result/Xeyth.Result.csproj

    - name : Copy README.md
      run: cp ../README.md Xeyth.Result/

    - name: Pack
      run: dotnet pack --no-build --configuration Release -o ./artifacts

    - name: Publish to NuGet
      if: success()  # Only run if previous steps succeed
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
